# Generated by Django 5.1.4 on 2025-01-19 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgm', '0002_category_alter_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('Mobile', 'Mobile')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='datefield',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
