# Generated by Django 5.1.4 on 2025-01-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgm', '0007_alter_stock_category_alter_stock_issue_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgm.category'),
        ),
    ]
